name: Build/release Electron app

on:
  push:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm run build

      - name: Run Electron Builder
        if: ${{ matrix.platform != 'mac' }}
        run: |
            npx electron-builder --${{ matrix.platform }} --publish always
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Electron Builder
        if: ${{ matrix.platform == 'mac' }}
        run: |
          echo "$API_KEY" > apple.p8
          npx electron-builder --${{ matrix.platform }} --publish always
        env:
          DEBUG: "*"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
          APPLE_API_KEY: apple.p8
          APPLE_API_KEY_ID: ${{ secrets.API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.API_KEY_ISSUER_ID }}
